### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by innerout** [thoni56/c-xrefactory#29] opened 2018-01-21 23:40 UTC
It would be useful to have better documentation on each feature because at the moment if somebody wants to use the plugin he does not know  what function to call.I am talking about emacs function calls.

**Comment by thoni56** [comment] 2018-01-22 07:18
Yes, in my effort to resurrect this project to a more modern state I've been thinking about at least a Cheat Sheet.

But it's interesting that you mention 'emacs function calls'. I haven't even thought about that. I've been thinking about `c-xrefactory` mostly as a user-facing functionality. Could you give a few examples of how/what you wanted to do?

**Comment by innerout** [comment] 2018-01-22 10:41
If i have understood correctly c-xrefactory is a cli program that supports refactoring go-to-definion and extract-function at least.So in the INSTALL file in the root directory directory of the project, it is said to take the c-xrefactory.el and c-xref.el to use it inside Emacs. But in order to use it in emacs we need to know the names of the functions to call in c-xref. If i want to rename a function name in my project what should i call inside Emacs. For example something like that (M-x c-xrefactory-refactor).

**Comment by thoni56** [comment] 2018-01-22 10:50
Ok, but if you let `c-xrefactory` install itself in your Emacs, preferably using `el-get` (`M-x el-get-install c-xrefactory`) then you will have a `C-xref` menu available in Emacs. So you don't have to call the functions from `M-x`, you can use the menu for most things.

On that menu you will find e.g. `Browsing with Symbol Stack`, not the most obvious name, but anyway, it's there ;-)

Perhaps this should be made more clear in the thin documentation there is now. Could you point me to where you tried to read about this, so I know where to start thinking about adding some comments about this. Or a pull request is also welcome.

**Comment by innerout** [comment] 2018-01-22 11:03
I read it from the Readme in the TL;DR section but i can not seem to make the menu appear in my emacs. I just ran the el-get command.

**Comment by thoni56** [comment] 2018-01-22 11:08
I've just added the function keys to that short description in the `README.md` for future readers.

I'm not sure I can help with the menu, though. One thing that bit me on one system was that I installed `el-get` with its quick&lazy installer snippet, but that only works for the current session. If you don't add the "permanent" `el-get` stuff to you `.emacs.d/init.el` you won't get the menu because things installed with `el-get` needs to be activated by `el-get` at Emacs startup also.

**Comment by innerout** [comment] 2018-01-22 11:10
OK i am going to try it later and i will answer if it got fixed.Your help is much appreciated.

**Comment by innerout** [comment] 2018-01-23 00:04
As it seems the problem was el-get,C-xref appeared after setting up the el-get configuration.Moreover i have one more suggestion for the documentation.Could it be possible to have a better description on how to use C-xref in a project, as it is not straightforward how to utilize it inside a project.I am always talking from the emacs perspective.Also i could help with the documentation after i can figure out how to use it in a project. To be more precise suppose we have project Xref 
Step 1 Create the database for the tags 
Step 2 Create the database for the index
Step 3 Create the database for the files
Something like that could be really useful so whoever comes could use the c-xref  with little effort.

**Comment by thoni56** [comment] 2018-01-23 08:34
Good. I'm happy that you made it work, and that it was `el-get` ;-)

Could you have a look at C-Xref -> C-xref Misc -> C-xref Help, please? I know it isn't as visible/obvious where to find it, but there is some description there. I've also, triggered by this discussion, updated it a bit. So if you `M-x el-get-update` the `c-xrefactory` package, you should get the latest help info.

Let me know if that information lacks something important.

**Comment by innerout** [comment] 2018-01-23 10:54
OK i can understand some things better now.When i press on the new project button then it says 
```Wrong type argument : stringp, nil```

**Comment by thoni56** [comment] 2018-01-24 07:17
Could you describe more details about when that error happened? Buffer visiting a file? I can’t reproduce. 

Does it happen if you visit a file, place the point on a variable and press F6 without any project activate or created?

**Comment by innerout** [comment] 2018-01-24 17:53
So i have never created c-xref database in any of my projects.I open one of the files of a random project in emacs and then i try to create a database for the project with c-xref.If i press f6 the same thing occurs.

**Comment by innerout** [comment] 2018-01-24 17:56
If i create Ctags for the project some functions for example go-to-definition works but i cannot refactor for example.

**Comment by thoni56** [comment] 2018-01-24 20:41
I'm not sure I understand what you are saying is happening here. Can you try to visit a C file that is not part of any project you have, if any. Then press F6. When you do that `c-xrefactory` will start prompting you for information about creating a project. First question will be

    No project covers <file>,
    create project?
    ---
    Yes
    No
    ---

Then you will get a number of questions. In the end `c-xrefactory` will generate the cross-reference database for the project it just created for you.

At which point in this process do you get `Wrong type argument : stringp, nil`? Or don't you get this at all?

(You should *not* need to specifically create a project.)

**Comment by innerout** [comment] 2018-01-24 20:42
It asks for the question you just typed and i press enter after i highlight yes.Is that wrong?

**Comment by thoni56** [comment] 2018-01-24 20:55
That is correct. Then you get questions like "name of project", "where to store tags", "is it a big project", "C and/or Java" etc. and then "Can I generate tags for the project now?" and finally "View log?"

After that you should be able to browse symbols, rename and extract.

**Comment by innerout** [comment] 2018-01-24 20:56
When i press enter on yes it prints  ```Wrong type argument : stringp, nil```

**Comment by thoni56** [comment] 2018-01-24 20:58
Hmm, never seen that. Can you turn on `debug-on-error` and paste the stack here? I'm not an expert Emacs elisp programmer so I'm a bit out of my depth here, but at least that might give a clue to the problem.

**Comment by thoni56** [comment] 2018-01-24 20:58
What's your Emacs version? System?

**Comment by innerout** [comment] 2018-01-24 20:59
Arch Linux with latest updates and Emacs 25.3.2.Never had a problem with Emacs though.

**Comment by thoni56** [comment] 2018-01-24 21:09
Ok, should be no problem then.

**Comment by innerout** [comment] 2018-01-24 21:34
![screenshot from 2018-01-24 23-34-22](https://user-images.githubusercontent.com/11080614/35358378-23c6df3c-015f-11e8-9192-d7fa338cd09c.png)
The Image is the output of debug-on-error.

**Comment by thoni56** [comment] 2018-01-25 06:58
From a quick look at that stack it looks like `c-xrefactory` and `helm` isn't cooperating. I have no clue to why that would be. Could you try turning `helm` off just to see if that works?

**Comment by innerout** [comment] 2018-01-25 09:54
After disabling Helm everything worked perfectly.Could you add support for Helm?

**Comment by thoni56** [comment] 2018-01-25 10:32
Ok, thanks, good to know. I don't know what supporting `helm` means, but could you, please, add an issue for that? Then I'll close this issue.

**Comment by thoni56** [comment] 2018-01-25 19:44
With some pointers to where documentation actually exists, we close this one.

**Closed as completed by thoni56** 2018-01-25 19:44 UTC
